// Local Recipe Data in array of objects represntation

let localRecipe = [
  {
    id: "cheese-burger",
    name: "Cheese Burger",
    ingredients: [
      "4 halved burger buns",
      "3 medium (boiled",
      "mashed,peeled) potato",
      "1/2 finely chopped capsicum (green pepper)",
      "2 tablespoon American corn kernels",
      "80 gm shredded cabbage",
      "2 tablespoon refined oil",
      "2 pinches white pepper powder",
      "1/2 gm sliced tomato",
      "4 medium cheese slices",
      "1 1/2 small finely chopped carrot",
      "1 sliced onion",
      "1 tablespoon butter",
      "2 pinches salt",
      "2 teaspoon tomato ketchup",
      "1/2 medium sliced cucumber",
    ],
    procedure: [
      "To prepare this easy cheesy burger, put a pan on medium flame and heat oil in it. Once the oil is sufficiently hot, add the chopped onions, carrots, capsicum and saute these ingredients for few minutes. Then add tomato ketchup in it and give it a nice stir. Once these ingredients are sauteed properly, remove them from the flame and transfer to a glass bowl.",
      "Now, add mashed potatoes in this veggie mixture and sprinkle salt and white pepper powder in it. Mix all the ingredients well and take portions of the mixture. Shape them into 4 round patties. Meanwhile, add butter in a non-stick pan and heat it over medium flame. Add the prepared patties and fry them for 30 seconds on both sides or until lightly browned.",
      "Bring the flame to low and and then, add a cheese slice on top of the patties. Cover with a lid and cook for another 30 seconds or until the cheese starts to melt. Then, slice the burger buns into halves and warm them slightly. Spread butter on one half of the burger buns.",
      "Now, add some cabbage on it, and top it up with tomato slices, cucumber and onion slice. Place the cooked burger patty with the cheese on top. Sprinkle a bit of pepper powder and top up with some sauce of your choice. You can also use different dressings of your choice. Cover with the other half of the bun and serve the scrumptious burger with fries and potato wedges.",
    ],
    src: "/images/cheese-burger.jpg",
  },
  {
    id: "french-fries-with-dip",
    name: "French Fries",
    ingredients: [
      "4 Potatoes",
      "1 Tsp Cinnamon Powder",
      "1 Tsp Coriander Powder",
      "1 Tsp Cumin Powder",
      "1 Tsp Black Pepper Powder",
      "3 Tbsp Garlic Powder",
      "1 Tsp Oregano Powder",
      "1 Tsp Kashmiri Red Chilli Powder",
      "Pinch Of Turmeric",
      "Salt As Needed",
      "Oil For Deep Frying",
    ],
    procedure: [
      "To prepare this easy recipe, you need to make sure that they are cut in the right shape and size. They should neither be too thick, nor too thin and should be cut clean and sharp. The trick is to first slice the potatoes and then cut them lengthwise. You can also use a fries cutter for that long, even shape.",
      "Now, wash the potatoes under running water till they are squeaky clean. Place them in a bowl of iced water for 10 to 15 minutes. Keep them submerged in water or they will turn black.",
      "Now, heat the oil in a deep bottomed pan. Once the smoke starts appearing, reduce the flame and allow it to acquire a lower temperature. Now, deep fry the potatoes in batches. Keep the flame low. This will make them crunchy and also help retain their colour.",
      "Drain excess oil and place them on an absorbent paper. Allow them to cool. Now sprinkle salt and pepper and toss well. Serve immediately with ketchup. They can also be served with burgers and cutlets.",
    ],
    src: "/images/french-fries-with-dip.jpg",
  },
  {
    id: "pancake-with-honey",
    name: "Pancake with Honey",
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "2 tablespoons sugar",
      "2 teaspoons baking powder",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "1 cup milk or buttermilk",
      "2 large eggs",
      "1/4 cup melted butter",
      "honey",
    ],
    procedure: [
      "In a large bowl, sift together the flour, baking powder, salt and sugar. Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.",
      "Heat a lightly oiled griddle or frying pan over medium-high heat. Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides.",
      "Serve hot with some honey on top.",
    ],
    src: "/images/pancake-with-honey.jpg",
  },
  {
    id: "red-pasta",
    name: "Red Pasta",
    ingredients: [
      "2 tablespoons olive oil",
      "½ medium onion",
      "finely diced",
      " ½ teaspoon red chili flakes",
      "1 clove garlic",
      "minced",
      "14 oz crushed tomato (395 g)",
      "salt to taste",
      "½ lb penne pasta (225 g)",
    ],
    procedure: [
      "Cook the tomatoes in a pan.",
      "Add the clove of garlic, onion and bay leaf to it.",
      "Add water and then season with salt and sugar.",
      "Cover and let the tomatoes boil.",
      "Cool and then grind to a puree.",
      "Now in a separate pan, heat oil and add chopped onions and chopped garlic.",
      "Add the tomato puree. Cook till its reduces to half.",
      "Add basil leaves and keep aside.",
      "Boil water with salt.",
      "Add the pasta to it and let it boil. Drain when done.",
      "Transfer in a serving dish and serve with the tomato sauce.",
    ],
    src: "/images/red-pasta.jpg",
  },
  {
    id: "white-pasta",
    name: "White Pasta",
    ingredients: [
      "1 lb penne pasta",
      "3 tbsp butter",
      "2 tsp minced garlic",
      "3 tbsp flour",
      "1 cup chicken broth",
      "1 cup milk",
      "2 tsp dried parsley",
      "1 cup grated parmesan cheese",
      "salt and pepper to taste",
    ],
    procedure: [
      "For preparing this pasta recipe, add water, oil and 1 tsp salt in a container. Heat it for a minute on high flame. Keep stirring time to time. Add pasta to it and heat it for additional 10 minutes on medium flame. Make sure that the pasta is boiled properly as sometimes it may take some extra time. Keep stirring in between so that the pasta doesn't stick to the bottom of the container. After boiling, drain out the water from pasta.",
      "Chop all the vegetables into small pieces and keep them aside. Add butter in a pan and heat it for 30 seconds over moderate flame. Now add onions in the pan and saute it for 2 minutes or till they turn slightly pinkish in colour. Add mushroom, baby corn, capsicum, oregano and saute them for 5 minutes.",
      "Add cornflour to the cooked vegetables in the pan and keep stirring. Add salt, pepper, red chilli flakes, milk and simmer it for another 5-6 minutes. Now add cream and boiled pasta to the mixture and heat it for 2 minutes.",
      "Garnish with cheese and grill it for 5 minutes. Hot white sauce pasta is ready to serve. Garnish with oregano seasoning and chilli flakes. Enjoy!",
    ],
    src: "/images/white-pasta.jpg",
  },
  {
    id: "seekh-kebab",
    name: "Seekh Kebab",
    ingredients: [
      "1.1 pounds (500 grams) ground lamb",
      "1 medium onion",
      "finely chopped",
      "1/2 cup fresh coriander",
      "chopped",
      "2 tablespoons unsweetened plain yogurt",
      "2 tablespoons lemon juice",
      "1 tablespoon garlic paste",
      "1 tablespoon ginger paste",
      "1 1/2 teaspoons kosher salt",
      "1 teaspoon garam masala",
      "2 to 3 green chilies",
      "finely chopped",
      "4 tablespoons vegetable oil, or as needed",
    ],
    procedure: [
      "Gather the ingredients.",
      "Place all seekh kebab ingredients except the oil and onion rings into a large mixing bowl.",
      "Use your hands or a spoon to mix the ingredients thoroughly until they are well blended. Cover and refrigerate for 2 hours or until the mixture is firm.",
      "Divide the meat mix into 4 to 6 equal portions. Take each portion and form it into a long sausage-like kebab while pressing onto a flat metal skewer. Do this until the mix has firmly adhered to the skewer. Use some oil on your hands to prevent the meat from sticking to them. Repeat the process with each portion.",
      "Place skewered kebabs on a platter or small baking sheet. If not cooking right away, cover with cling film and keep refrigerated.",
      "Heat grill to medium-high. Grease the grill grates with oil to avoid sticking. If you can, use a fine grate to place the kebabs on. Grill the kebabs until the meat is done. Turning often gives the kebabs an even crusty exterior and helps with even cooking. The minimum safe temperature for lamb consumption is 145 F—if possible, check with an instant-read thermometer.",
      "Place the raw onion rings on a serving plate. Transfer the cooked kebabs onto the plate and, if working in batches, loosely tent with foil until you're done cooking the rest of the kebabs. Serve hot.",
    ],
    src: "/images/sheek-kebab.jpg",
  },
  {
    id: "chocolate-cupcake",
    name: "Chocolate Cupcake",
    ingredients: [
      "1 cup (130g) all purpose flour",
      "1 cup (207g) sugar",
      "6 tbsp (43g) unsweetened cocoa powder",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "1 large egg",
      "1/2 cup (120ml) buttermilk",
      "1/2 cup (120ml) vegetable oil",
      "3/4 tsp vanilla",
      "1/2 cup (120ml) hot water",
      "1 1/4 cups (280g) unsalted butter, room temperature",
      "12 oz semi sweet chocolate chips, melted",
      "3 tbsp (22g) Hershey’s dark cocoa powder",
      "5 cups (575g) powdered sugar",
      "Pinch of salt",
      "4–5 tbsp (60-75ml) heavy whipping cream",
    ],
    procedure: [
      "Preheat oven to 300°F (148°C) and prepare a cupcake pan with liners.",
      "Add the dry ingredients to a large bowl and whisk together. Set aside.",
      "Combine the egg, buttermilk, vegetable oil and vanilla in another medium sized bowl.",
      "Add the wet ingredients to the dry ingredients and mix until well combined.",
      "Add the water to the batter and mix until well combined. Batter will be thin.",
      "Fill the cupcake liners about half way and bake for 18-23 minutes, or until a toothpick comes out with a few moist crumbs.",
      "Remove the cupcakes from oven and allow to cool for 2 minutes, then remove to a cooling rack to finish cooling.",
      "To make the frosting, beat the butter in a large mixer bowl and mix until smooth.",
      "Add the melted chocolate and mix until well combined.",
      "Add the cocoa powder and mix until well combined.",
      "Add about half of powdered sugar and 2 tablespoons of heavy cream and mix until well combined.",
      "Add remaining powdered sugar and salt and mix until smooth.",
      "Add remaining heavy cream as needed to get the right consistency of frosting.",
      "Pipe the frosting onto the cupcakes. I used Ateco tip 844.",
    ],
    src: "/images/chocolate-cupcake.jpg",
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    ingredients: [
      "¾ cup (100 grams) milk powder, unsweetened",
      "½ cup (60 grams) maida/plain flour",
      "½ tsp baking powder",
      "2 tbsp ghee/clarified butter",
      "milk (for kneading)",
      "ghee or oil (for frying)",
      "2 cup sugar",
      "2 cup water",
      "2 cardamom",
      "¼ tsp saffron / kesar",
      "1 tsp lemon juice",
      "1 tsp rose water",
    ],
    procedure: [
      "firstly, in a large bowl take ¾ cup milk powder, ½ cup maida and ½ tsp baking powder.",
      "Mix well, homemade gulab jamun mix is ready.",
      "Now add 2 tbsp ghee and mix well making the flour moist.",
      "Further, add milk as required start to combine.",
      "Combine well forming a soft dough. do not knead the dough.",
      "Cover and rest for 10 minutes.",
      "Meanwhile, prepare the sugar syrup by taking 2 cup sugar, 2 cup water, 2 cardamom and ¼ tsp saffron.",
      "Mix well and boil for 5 minutes or until the sugar syrup turns sticky. do not attain any string consistency.",
      "Turn off the flame and add 1 tsp lemon juice and 1 tsp rose water. lemon juice is added to prevent sugar syrup from crystallizing.",
      "Cover and keep the sugar syrup aside.",
      "After 10 minutes or resting the dough, start to prepare small ball sized jamuns.",
      "Make sure there are no cracks in the jamun. if there are cracks then there are high chances for jamuns to break while frying.",
      "Deep fry in medium hot oil or ghee. frying in ghee gives good flavour to jamuns.",
      "Stir continuously and fry on low flame.",
      "Fry until the jamuns turn golden brown.",
      "Drain off and transfer the jamun into a hot sugar syrup.",
      "Cover and rest for 2 hours or until jamuns absorb the sugar syrup and doubles in size.",
      "Finally, enjoy gulab jamun with ice cream or as it is.",
    ],
    src: "/images/gulab-jamun.jpg",
  },
];

export { localRecipe };
